lab1/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace lab1.Controllers
{
    public class AuthController : Controller
    {
        // GET: Auth
        public ActionResult Auth()
        {
            return View();
        }
        public ActionResult Registration()
        {
            return View();
        }
    }
}

lab1/Controllers/DefaultController.cs
using lab1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace lab1.Controllers
{
    public class DefaultController : Controller
    {
        siteEntities1 db = new siteEntities1();
        //ArticleContext db = new ArticleContext();
        // GET: Default
        public ActionResult Test_View()
        {
            return View();
        }
        public ActionResult Profile()
        {
            return View();
        }
        public ActionResult EditProfile()
        {
            return View();
        }
        public ActionResult AddArticle()
        {
            return View();
        }

        public ActionResult Article(int identity)
        {
            List<Article> articles = db.Article.ToList<Article>();
            foreach (var a in articles)
            {
                if (a.id_article == identity)
                {
                    ViewBag.Article = a;
                    ViewBag.Followed = "Follow";
                    List<Users> users = db.Users.ToList<Users>();

                    foreach (Users u in users)
                    {
                        if (u.id_user == 2)
                        {
                            if (u.fllow.IndexOf(a.id_article.ToString()) >= 0)
                            {
                                ViewBag.Followed = "Followed";
                            }

                        }
                    }
                    Console.WriteLine(a.head);
                }
            }
            return View();
        }

        public ActionResult EditArticle(int identity)
        {
            List<Article> articles = db.Article.ToList<Article>();
            foreach (var a in articles)
            {
                if (a.id_article == identity)
                {
                    ViewBag.Article = a;

                }
            }
            return View();
        }
        public ActionResult AllArticles()
        {
            List<Article> articles = db.Article.ToList<Article>();

            ViewBag.Articles = articles;

            ViewBag.Articles = articles;

            return View();
        }


        public ActionResult AddAction()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddAction(string head, string body, string file)
        {
            Article a = new Article();
            a.head = head;
            a.body = body;
            a.data = DateTime.Now;
            a.image = file;
            a.id_user = 2;

            //db.Article.Add(a);
            db.Database.ExecuteSqlCommand("insert into Article (id_user,head,body,data,image) values(2," +
                "'" + head + "','" + body + "','" + a.data.ToString() + "','" + file + "')");
            db.SaveChanges();
            return Content("Спасобо, скоро опубликуем)");
        }
        public ActionResult EditAction()
        {
            return View();
        }
        [HttpPost]
        public ActionResult EditAction(string head, string body, string file, string id_article)
        {
            Article a = new Article();
            a.head = head;
            a.body = body;
            a.data = DateTime.Now;
            a.image = file;
            a.id_user = 2;

            //db.Article.Add(a);
            db.Database.ExecuteSqlCommand("update Article set head='" + head + "',body='" + body + "',data='" + a.data.ToString() + "',image='" + file + "' where id_article=" + id_article);
            db.SaveChanges();
            return Content("Спасобо, скоро опубликуем)");
        }



        public ActionResult FollowAction()
        {
            return View();
        }
        [HttpPost]
        public ActionResult FollowAction(string type, string id, string file)
        {
            Users user = new Users();
            List<Users> users = db.Users.ToList<Users>();
            foreach (Users u in users)
            {
                if (u.id_user == 2)
                {
                    user = u;
                }
            }
            if (type == "Follow")
            {

                string followList = user.fllow.ToString();
                followList += ',' + id;
                db.Database.ExecuteSqlCommand("update dbo.Users set fllow='" + followList + "' where id_user=2;");
                
                /*db.Database.ExecuteSqlCommand("insert into Article (id_user,head,body,data,image) values(2," +
                "'" + head + "','" + body + "','" + a.data.ToString() + "','" + file + "')");
                return Content("follow)");*/
            }
            if (type == "Followed")
            {
                string followList = user.fllow.ToString();
                followList = followList.Replace((',' + id),"");
                db.Database.ExecuteSqlCommand("update dbo.Users set fllow='" + followList + "' where id_user=2;");
                return Content("Спасобо, скоро удалим подписку)");
            }

            if (type == "Delete")
            {
                string followList = user.fllow.ToString();
                followList.Replace(',' + id, "");
                db.Database.ExecuteSqlCommand("delete from dbo.Article where  id_article=" + id);
                return Content("Спасобо, скоро удалим статью)");
            }


            //db.Article.Add(a);
            /*db.Database.ExecuteSqlCommand("insert into Article (id_user,head,body,data,image) values(2," +
                "'" + head + "','" + body + "','" + a.data.ToString() + "','" + file + "')");
            db.SaveChanges();*/
            return Content("Спасобо, скоро опубликуем)");
        }
    }
}

lab1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
  
    @Styles.Render("~/Content/index.css")

    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Scripts/jquery-3.3.1.min.js")
    @Scripts.Render("~/Scripts/bootstrap.min.js")
</head>
<body>
    <nav class="nav navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <p class="navbar-brand">@Html.ActionLink("Photo Learn", "Index", "Home")</p>
               
            </div>


            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        @Html.ActionLink("Подборка статей", "AllArticles", "Default")
                        
                    </li>
                    <li>
                        @Html.ActionLink("Профиль", "Profile", "Default")
                    </li>
                    <li>
                        <a href="#Contacts">Контакты</a>
                    </li>

                    <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            Авторизация
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                @Html.ActionLink("Вход", "Auth", "Auth")
                            </li>
                            <li>
                                @Html.ActionLink("Регистрация", "Registration", "Auth")
                            </li>
                        </ul>
                    </li>

                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
   
   
        @RenderBody()




        <hr />
    <div class="footer-bottom">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 ">
                    <div class="copyright-text">
                        <p>CopyRight © 2017 Digital All Rights Reserved</p>
                    </div>
                </div>
                <!-- End Col -->
                <div class="col-sm-6">
                    <ul class="social-link pull-right">
                        <li>
                            <a href="">
                                <span class="glyphicon glyphicon-heart-empty"></span>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <span class="glyphicon glyphicon-heart-empty"></span>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <span class="glyphicon glyphicon-heart-empty"></span>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <span class="glyphicon glyphicon-heart-empty"></span>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <span class="glyphicon glyphicon-heart-empty"></span>
                            </a>
                        </li>
                    </ul>
                </div>
                <!-- End Col -->
            </div>
        </div>
    </div>
   

    @RenderSection("scripts", required: false)
</body>
</html>